# Generated by Django 2.2.12 on 2020-06-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
