# Generated by Django 2.2.12 on 2020-06-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
